### ISSUE TITLE
Will you plan to make this available via FreeCAD addon manager ?

### ISSUE THREAD

**Issue by luzpaz** [execuc/LCInterlocking#14]
https://github.com/FreeCAD/FreeCAD-addons

**Comment by luzpaz** [comment]
CC @probonopd

**Comment by execuc** [comment]
I do not think to integrate it into freecad addon manager because I'm not happy with the way I integrated it in the HMI.
Indeed I would have liked to see the parameters of this tool in the View part and not in another window. Which prevents to update the parameters of created parts without starting all over again.

**Comment by luzpaz** [comment]
Would you be open to collaborate with the FreeCAD community, by posting your thoughts in a post and see if anyone would be interested in revising this ?

**Comment by execuc** [comment]
I started to look at how to create items in the model tree view. I think it's not easy without too much modification. I will work on it. 
I see that some people are interested in this plugin, so I will try to improve it.

**Comment by luzpaz** [comment]
Feel free to get any assistance on the forums.

**Comment by execuc** [comment]
OK, thank you !

**Comment by execuc** [comment]
Module is now improved. All tools can now be reedited.

**Comment by luzpaz** [comment]
Available via FC AddonManager
