### ISSUE TITLE
Interlocking is not working in freecad 0.18.4

### ISSUE THREAD

**Issue by fabricioncosta** [execuc/LCInterlocking#39]
Hi, 

I could not use this functionality. I follow all the steps described  on the tutorial (https://www.youtube.com/watch?v=YGFIdLpdWXE&feature=youtu.be)  and it did not generating any error message, but the final result is the same box I have created (without interlocking)

https://www.youtube.com/watch?v=YGFIdLpdWXE&feature=youtu.be
Freecad: 0.18.4.

Could you help me? 

Thanks,

**Comment by execuc** [comment]
Hi,

The video is old and does not show the change I made in the interface. Now, a 'Multijoin' object is created at the end of the interlocking tool.

In interlocking tool, do you have created the "faces" (with 'add faces' or 'add same face' button) in the main window and not in the preview window (preivew button) ?

Do not hesitate to upload print screens or FreeCAD file which could help me reproduce the problem.

Thanks

**Comment by fabricioncosta** [comment]
Hi,
Multijoin object continue to be created at the begining (before selected the parts in interlocking tool). I am using freecad 0.18.4 and the last version of LCIterlocking installed manually.  I have just created a box (make a box without tab) with this parameters:

![Capture1](https://user-images.githubusercontent.com/14183494/73296376-5c00dd00-41e8-11ea-8acd-b0c40fa4a21b.PNG)

and runned "interloking" with all the parts added:

![Capture2](https://user-images.githubusercontent.com/14183494/73296438-7f2b8c80-41e8-11ea-8cb3-5c7e559b7523.PNG)

The final result do not have the tabs and pads, as expected:

![Capture3](https://user-images.githubusercontent.com/14183494/73296535-a84c1d00-41e8-11ea-951f-6e2946bd159f.PNG)

Thanks,

**Comment by execuc** [comment]
Hi,

Thank you for describing the problem with images which I understand.
In fact, "interlocking" tools has two steps:
- Define all the parts and set options (thickness, laser beam...)
- Declare all the faces which must have tabs.

I think it's this second step that is missing. For each faces (or group of faces), you have to select them and click on 'add face' (or 'add same face') . Three types of tab exist and must be selected from the drop-down menu before pressing the 'add face' button. Depending on the type of tab, you must configure the tab options (size, repetition ...

Sometimes it's a bit tricky to select faces because you have to hide parts with the space key and then display them again

There is a short documentation for this tool: https://github.com/execuc/LCInterlocking/blob/master/docs/interlocking.md

I have found a video on youtube : https://youtu.be/6sKECZwBjZk

**Comment by fabricioncosta** [comment]
Hi,

Now I could generate the interlocking! 

![image](https://user-images.githubusercontent.com/14183494/73372568-37633e80-4296-11ea-9b6d-4b7cdd5407f1.png)

Thank you very much!

**Comment by execuc** [comment]
You're welcome !
